### PR TITLE
Cloudpro

### PR DESCRIPTION
**Pull request by kunskytested**
problem
Need to create vpc

Solution
Created vpc

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Review by Mummycutie — APPROVED** [review]
LGTM

**Review by Charles123Bob-Duru — COMMENTED** [review]
LGTM

**Review by Charles123Bob-Duru — APPROVED** [review]

**Review by tberry147 — CHANGES_REQUESTED** [review]
Please change to default region us-east-1

**Review by tberry147 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
